import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.Sidebar = {
  '/system-design/': [
    {
      text: 'System Design',
      items: [
        { text: 'Overview', link: '/system-design/' },
      ],
    },
    {
      text: 'Distributed Systems',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/system-design/distributed-systems/' },
        { text: 'CAP Theorem', link: '/system-design/distributed-systems/cap-theorem' },
        { text: 'Consistency Models', link: '/system-design/distributed-systems/consistency-models' },
        { text: 'Distributed Transactions', link: '/system-design/distributed-systems/distributed-transactions' },
        { text: 'Vector Clocks & Lamport Timestamps', link: '/system-design/distributed-systems/vector-clocks-lamport-timestamps' },
        { text: 'Gossip Protocols', link: '/system-design/distributed-systems/gossip-protocols' },
        { text: 'Consistent Hashing', link: '/system-design/distributed-systems/consistent-hashing' },
        { text: 'Byzantine Fault Tolerance', link: '/system-design/distributed-systems/byzantine-fault-tolerance' },
        { text: 'CRDTs', link: '/system-design/distributed-systems/crdt-fundamentals' },
        { text: 'Distributed Snapshots', link: '/system-design/distributed-systems/distributed-snapshots' },
        { text: 'Failure Detectors', link: '/system-design/distributed-systems/failure-detectors' },
        { text: 'Clock Synchronization', link: '/system-design/distributed-systems/clock-synchronization' },
      ],
    },
    {
      text: 'Databases',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/system-design/databases/' },
        { text: 'Storage Engines', link: '/system-design/databases/storage-engines' },
        { text: 'Write-Ahead Logging', link: '/system-design/databases/write-ahead-logging' },
        { text: 'MVCC', link: '/system-design/databases/mvcc' },
        { text: 'Isolation Levels', link: '/system-design/databases/isolation-levels' },
        { text: 'Indexing Deep Dive', link: '/system-design/databases/indexing-deep-dive' },
        { text: 'Query Planning & Optimization', link: '/system-design/databases/query-planning-optimization' },
        { text: 'Connection Pooling', link: '/system-design/databases/connection-pooling' },
        { text: 'Replication', link: '/system-design/databases/replication' },
        { text: 'Sharding', link: '/system-design/databases/sharding' },
        { text: 'PostgreSQL Internals', link: '/system-design/databases/postgres-internals' },
        { text: 'Redis Internals', link: '/system-design/databases/redis-internals' },
        { text: 'MongoDB Internals', link: '/system-design/databases/mongodb-internals' },
        { text: 'Database Selection Guide', link: '/system-design/databases/database-selection-guide' },
        { text: 'Time-Series Databases', link: '/system-design/databases/time-series-databases' },
        { text: 'Graph Databases', link: '/system-design/databases/graph-databases' },
        { text: 'NewSQL', link: '/system-design/databases/newsql' },
      ],
    },
    {
      text: 'Caching',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/system-design/caching/' },
        { text: 'Caching Strategies', link: '/system-design/caching/caching-strategies' },
        { text: 'Cache Invalidation', link: '/system-design/caching/cache-invalidation' },
        { text: 'Thundering Herd', link: '/system-design/caching/thundering-herd' },
        { text: 'Cache Warming', link: '/system-design/caching/cache-warming' },
        { text: 'Multi-Layer Caching', link: '/system-design/caching/multi-layer-caching' },
        { text: 'Cache Sizing Math', link: '/system-design/caching/cache-sizing-math' },
        { text: 'Redis Caching Patterns', link: '/system-design/caching/redis-caching-patterns' },
        { text: 'CDN Deep Dive', link: '/system-design/caching/cdn-deep-dive' },
      ],
    },
    {
      text: 'Message Queues',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/system-design/message-queues/' },
        { text: 'Kafka Internals', link: '/system-design/message-queues/kafka-internals' },
        { text: 'RabbitMQ Internals', link: '/system-design/message-queues/rabbitmq-internals' },
        { text: 'Redis Streams', link: '/system-design/message-queues/redis-streams' },
        { text: 'SQS & SNS', link: '/system-design/message-queues/sqs-sns' },
        { text: 'NATS', link: '/system-design/message-queues/nats' },
        { text: 'Apache Pulsar', link: '/system-design/message-queues/pulsar' },
        { text: 'Backpressure Patterns', link: '/system-design/message-queues/backpressure-patterns' },
        { text: 'Dead Letter Queues', link: '/system-design/message-queues/dead-letter-queues' },
        { text: 'Ordering Guarantees', link: '/system-design/message-queues/ordering-guarantees' },
        { text: 'Exactly-Once Semantics', link: '/system-design/message-queues/exactly-once-semantics' },
        { text: 'Queue Selection Guide', link: '/system-design/message-queues/queue-selection-guide' },
      ],
    },
    {
      text: 'Consensus',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/system-design/consensus/' },
        { text: 'Raft Full Walkthrough', link: '/system-design/consensus/raft-full-walkthrough' },
        { text: 'Paxos Made Simple', link: '/system-design/consensus/paxos-made-simple' },
        { text: 'ZAB Protocol', link: '/system-design/consensus/zab-protocol' },
        { text: 'Viewstamped Replication', link: '/system-design/consensus/viewstamped-replication' },
        { text: 'Practical BFT', link: '/system-design/consensus/practical-bft' },
      ],
    },
    {
      text: 'Load Balancing',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/system-design/load-balancing/' },
        { text: 'L4 vs L7', link: '/system-design/load-balancing/l4-vs-l7' },
        { text: 'Algorithms', link: '/system-design/load-balancing/algorithms' },
        { text: 'Health Checks', link: '/system-design/load-balancing/health-checks' },
        { text: 'Session Affinity', link: '/system-design/load-balancing/session-affinity' },
        { text: 'Global Load Balancing', link: '/system-design/load-balancing/global-load-balancing' },
        { text: 'NGINX Config', link: '/system-design/load-balancing/nginx-config' },
        { text: 'HAProxy Config', link: '/system-design/load-balancing/haproxy-config' },
        { text: 'Envoy Config', link: '/system-design/load-balancing/envoy-config' },
      ],
    },
    {
      text: 'Networking',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/system-design/networking/' },
        { text: 'TCP/IP Deep Dive', link: '/system-design/networking/tcp-ip-deep-dive' },
        { text: 'HTTP/2 & HTTP/3', link: '/system-design/networking/http2-http3' },
        { text: 'gRPC Internals', link: '/system-design/networking/grpc-internals' },
        { text: 'WebSockets', link: '/system-design/networking/websockets' },
        { text: 'DNS Deep Dive', link: '/system-design/networking/dns-deep-dive' },
        { text: 'TLS Handshake', link: '/system-design/networking/tls-handshake' },
        { text: 'Service Discovery', link: '/system-design/networking/service-discovery' },
        { text: 'Network Debugging', link: '/system-design/networking/network-debugging' },
      ],
    },
  ],

  '/architecture-patterns/': [
    {
      text: 'Architecture Patterns',
      items: [
        { text: 'Overview', link: '/architecture-patterns/' },
      ],
    },
    {
      text: 'Microservices',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/architecture-patterns/microservices/' },
        { text: 'Decomposition Strategies', link: '/architecture-patterns/microservices/decomposition-strategies' },
        { text: 'Communication Patterns', link: '/architecture-patterns/microservices/communication-patterns' },
        { text: 'API Gateway Pattern', link: '/architecture-patterns/microservices/api-gateway-pattern' },
        { text: 'Service Mesh', link: '/architecture-patterns/microservices/service-mesh' },
        { text: 'Data Management', link: '/architecture-patterns/microservices/data-management' },
        { text: 'Testing Strategies', link: '/architecture-patterns/microservices/testing-strategies' },
        { text: 'Migration from Monolith', link: '/architecture-patterns/microservices/migration-from-monolith' },
        { text: 'Anti-Patterns', link: '/architecture-patterns/microservices/anti-patterns' },
      ],
    },
    {
      text: 'Event-Driven',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/architecture-patterns/event-driven/' },
        { text: 'Event Types', link: '/architecture-patterns/event-driven/event-types' },
        { text: 'Event Bus Patterns', link: '/architecture-patterns/event-driven/event-bus-patterns' },
        { text: 'Event Choreography', link: '/architecture-patterns/event-driven/event-choreography' },
        { text: 'Event Orchestration', link: '/architecture-patterns/event-driven/event-orchestration' },
        { text: 'Event Schema Evolution', link: '/architecture-patterns/event-driven/event-schema-evolution' },
        { text: 'Eventual Consistency', link: '/architecture-patterns/event-driven/eventual-consistency' },
      ],
    },
    {
      text: 'CQRS & Event Sourcing',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/architecture-patterns/cqrs-event-sourcing/' },
        { text: 'CQRS Deep Dive', link: '/architecture-patterns/cqrs-event-sourcing/cqrs-deep-dive' },
        { text: 'Event Sourcing Deep Dive', link: '/architecture-patterns/cqrs-event-sourcing/event-sourcing-deep-dive' },
        { text: 'Aggregate Design', link: '/architecture-patterns/cqrs-event-sourcing/aggregate-design' },
        { text: 'Projections', link: '/architecture-patterns/cqrs-event-sourcing/projections' },
        { text: 'Snapshots', link: '/architecture-patterns/cqrs-event-sourcing/snapshots' },
        { text: 'Sagas & Process Managers', link: '/architecture-patterns/cqrs-event-sourcing/sagas-process-managers' },
        { text: 'Event Upcasting', link: '/architecture-patterns/cqrs-event-sourcing/event-upcasting' },
      ],
    },
    {
      text: 'Hexagonal Architecture',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/architecture-patterns/hexagonal/' },
        { text: 'Ports & Adapters', link: '/architecture-patterns/hexagonal/ports-and-adapters' },
        { text: 'Dependency Inversion', link: '/architecture-patterns/hexagonal/dependency-inversion' },
        { text: 'TypeScript Implementation', link: '/architecture-patterns/hexagonal/typescript-implementation' },
      ],
    },
    {
      text: 'Clean Architecture',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/architecture-patterns/clean-architecture/' },
        { text: 'Layers & Boundaries', link: '/architecture-patterns/clean-architecture/layers-and-boundaries' },
        { text: 'Use Cases', link: '/architecture-patterns/clean-architecture/use-cases' },
        { text: 'Entities vs Models', link: '/architecture-patterns/clean-architecture/entities-vs-models' },
        { text: 'TypeScript Implementation', link: '/architecture-patterns/clean-architecture/typescript-implementation' },
      ],
    },
    {
      text: 'Domain-Driven Design',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/architecture-patterns/domain-driven-design/' },
        { text: 'Strategic Design', link: '/architecture-patterns/domain-driven-design/strategic-design' },
        { text: 'Tactical Design', link: '/architecture-patterns/domain-driven-design/tactical-design' },
        { text: 'Domain Events', link: '/architecture-patterns/domain-driven-design/domain-events' },
        { text: 'Anti-Corruption Layer', link: '/architecture-patterns/domain-driven-design/anti-corruption-layer' },
        { text: 'Specification Pattern', link: '/architecture-patterns/domain-driven-design/specification-pattern' },
        { text: 'TypeScript Implementation', link: '/architecture-patterns/domain-driven-design/typescript-implementation' },
      ],
    },
  ],

  '/infrastructure/': [
    {
      text: 'Infrastructure',
      items: [
        { text: 'Overview', link: '/infrastructure/' },
      ],
    },
    {
      text: 'Terraform',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/infrastructure/terraform/' },
        { text: 'Fundamentals', link: '/infrastructure/terraform/fundamentals' },
        { text: 'State Management', link: '/infrastructure/terraform/state-management' },
        { text: 'Modules', link: '/infrastructure/terraform/modules' },
        { text: 'Workspaces', link: '/infrastructure/terraform/workspaces' },
        { text: 'AWS Startup Stack', link: '/infrastructure/terraform/aws-startup-stack' },
        { text: 'GCP Startup Stack', link: '/infrastructure/terraform/gcp-startup-stack' },
        { text: 'Multi-Region', link: '/infrastructure/terraform/multi-region' },
        { text: 'Security Hardening', link: '/infrastructure/terraform/security-hardening' },
        { text: 'Cost Optimization', link: '/infrastructure/terraform/cost-optimization' },
      ],
    },
    {
      text: 'Kubernetes',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/infrastructure/kubernetes/' },
        { text: 'Architecture Internals', link: '/infrastructure/kubernetes/architecture-internals' },
        { text: 'Pod Lifecycle', link: '/infrastructure/kubernetes/pod-lifecycle' },
        { text: 'Deployments & StatefulSets', link: '/infrastructure/kubernetes/deployments-statefulsets' },
        { text: 'Services & Ingress', link: '/infrastructure/kubernetes/services-ingress' },
        { text: 'HPA, VPA & KEDA', link: '/infrastructure/kubernetes/hpa-vpa-keda' },
        { text: 'Network Policies', link: '/infrastructure/kubernetes/network-policies' },
        { text: 'RBAC', link: '/infrastructure/kubernetes/rbac' },
        { text: 'Secrets Management', link: '/infrastructure/kubernetes/secrets-management' },
        { text: 'Helm Charts', link: '/infrastructure/kubernetes/helm-charts' },
        { text: 'Operators', link: '/infrastructure/kubernetes/operators' },
        { text: 'Troubleshooting', link: '/infrastructure/kubernetes/troubleshooting' },
        { text: 'Production Checklist', link: '/infrastructure/kubernetes/production-checklist' },
      ],
    },
    {
      text: 'Docker',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/infrastructure/docker/' },
        { text: 'Internals', link: '/infrastructure/docker/internals' },
        { text: 'Multi-Stage Builds', link: '/infrastructure/docker/multi-stage-builds' },
        { text: 'Security Hardening', link: '/infrastructure/docker/security-hardening' },
        { text: 'Production Dockerfiles', link: '/infrastructure/docker/production-dockerfiles' },
        { text: 'Compose Patterns', link: '/infrastructure/docker/compose-patterns' },
        { text: 'Image Optimization', link: '/infrastructure/docker/image-optimization' },
      ],
    },
    {
      text: 'AWS',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/infrastructure/aws/' },
        { text: 'VPC & Networking', link: '/infrastructure/aws/vpc-networking' },
        { text: 'ECS vs EKS', link: '/infrastructure/aws/ecs-vs-eks' },
        { text: 'RDS & Aurora', link: '/infrastructure/aws/rds-aurora' },
        { text: 'ElastiCache', link: '/infrastructure/aws/elasticache' },
        { text: 'S3 & CloudFront', link: '/infrastructure/aws/s3-cloudfront' },
        { text: 'Lambda', link: '/infrastructure/aws/lambda' },
        { text: 'IAM Deep Dive', link: '/infrastructure/aws/iam-deep-dive' },
        { text: 'Cost Optimization', link: '/infrastructure/aws/cost-optimization' },
        { text: 'Well-Architected', link: '/infrastructure/aws/well-architected' },
      ],
    },
    {
      text: 'GCP',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/infrastructure/gcp/' },
        { text: 'Cloud Run', link: '/infrastructure/gcp/cloud-run' },
        { text: 'GKE', link: '/infrastructure/gcp/gke' },
        { text: 'Cloud SQL', link: '/infrastructure/gcp/cloud-sql' },
        { text: 'Pub/Sub', link: '/infrastructure/gcp/pub-sub' },
        { text: 'IAM', link: '/infrastructure/gcp/iam' },
        { text: 'Cost Optimization', link: '/infrastructure/gcp/cost-optimization' },
      ],
    },
    {
      text: 'CI/CD',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/infrastructure/ci-cd/' },
        { text: 'GitHub Actions Deep Dive', link: '/infrastructure/ci-cd/github-actions-deep-dive' },
        { text: 'GitLab CI', link: '/infrastructure/ci-cd/gitlab-ci' },
        { text: 'Pipeline Patterns', link: '/infrastructure/ci-cd/pipeline-patterns' },
        { text: 'Artifact Management', link: '/infrastructure/ci-cd/artifact-management' },
        { text: 'Environment Promotion', link: '/infrastructure/ci-cd/environment-promotion' },
        { text: 'Security Scanning', link: '/infrastructure/ci-cd/security-scanning' },
      ],
    },
    {
      text: 'Multi-Region',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/infrastructure/multi-region/' },
        { text: 'Architecture Patterns', link: '/infrastructure/multi-region/architecture-patterns' },
        { text: 'Data Replication', link: '/infrastructure/multi-region/data-replication' },
        { text: 'Traffic Routing', link: '/infrastructure/multi-region/traffic-routing' },
        { text: 'Failover Strategies', link: '/infrastructure/multi-region/failover-strategies' },
        { text: 'Cost Analysis', link: '/infrastructure/multi-region/cost-analysis' },
      ],
    },
  ],

  '/security/': [
    {
      text: 'Security',
      items: [
        { text: 'Overview', link: '/security/' },
      ],
    },
    {
      text: 'OWASP Top 10 (2021)',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/security/owasp/' },
        { text: 'A01: Broken Access Control', link: '/security/owasp/a01-broken-access-control' },
        { text: 'A02: Cryptographic Failures', link: '/security/owasp/a02-cryptographic-failures' },
        { text: 'A03: Injection', link: '/security/owasp/a03-injection' },
        { text: 'A04: Insecure Design', link: '/security/owasp/a04-insecure-design' },
        { text: 'A05: Security Misconfiguration', link: '/security/owasp/a05-security-misconfiguration' },
        { text: 'A06: Vulnerable Components', link: '/security/owasp/a06-vulnerable-components' },
        { text: 'A07: Auth Failures', link: '/security/owasp/a07-auth-failures' },
        { text: 'A08: Data Integrity Failures', link: '/security/owasp/a08-data-integrity-failures' },
        { text: 'A09: Logging & Monitoring', link: '/security/owasp/a09-logging-monitoring-failures' },
        { text: 'A10: SSRF', link: '/security/owasp/a10-ssrf' },
        { text: '2017 → 2021 Mapping', link: '/security/owasp/2017-to-2021-mapping' },
      ],
    },
    {
      text: 'Authentication',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/security/authentication/' },
        { text: 'JWT Deep Dive', link: '/security/authentication/jwt-deep-dive' },
        { text: 'OAuth2 & OIDC', link: '/security/authentication/oauth2-oidc' },
        { text: 'Session Management', link: '/security/authentication/session-management' },
        { text: 'MFA Implementation', link: '/security/authentication/mfa-implementation' },
        { text: 'Passwordless', link: '/security/authentication/passwordless' },
        { text: 'API Key Design', link: '/security/authentication/api-key-design' },
        { text: 'Biometric Auth', link: '/security/authentication/biometric-auth' },
      ],
    },
    {
      text: 'Encryption',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/security/encryption/' },
        { text: 'Symmetric vs Asymmetric', link: '/security/encryption/symmetric-vs-asymmetric' },
        { text: 'Hashing Algorithms', link: '/security/encryption/hashing-algorithms' },
        { text: 'Encryption at Rest', link: '/security/encryption/encryption-at-rest' },
        { text: 'Encryption in Transit', link: '/security/encryption/encryption-in-transit' },
        { text: 'Key Management', link: '/security/encryption/key-management' },
        { text: 'Envelope Encryption', link: '/security/encryption/envelope-encryption' },
      ],
    },
    {
      text: 'Secrets Management',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/security/secrets-management/' },
        { text: 'Vault Deep Dive', link: '/security/secrets-management/vault-deep-dive' },
        { text: 'AWS Secrets Manager', link: '/security/secrets-management/aws-secrets-manager' },
        { text: 'Rotation Automation', link: '/security/secrets-management/rotation-automation' },
        { text: 'Secrets in CI/CD', link: '/security/secrets-management/secrets-in-ci-cd' },
      ],
    },
    {
      text: 'Zero Trust',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/security/zero-trust/' },
        { text: 'Principles', link: '/security/zero-trust/principles' },
        { text: 'Identity Verification', link: '/security/zero-trust/identity-verification' },
        { text: 'Network Segmentation', link: '/security/zero-trust/network-segmentation' },
        { text: 'Least Privilege', link: '/security/zero-trust/least-privilege' },
        { text: 'Continuous Verification', link: '/security/zero-trust/continuous-verification' },
      ],
    },
    {
      text: 'API Security',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/security/api-security/' },
        { text: 'Rate Limiting', link: '/security/api-security/rate-limiting' },
        { text: 'Request Signing', link: '/security/api-security/request-signing' },
        { text: 'Input Validation', link: '/security/api-security/input-validation' },
        { text: 'CORS Deep Dive', link: '/security/api-security/cors-deep-dive' },
        { text: 'CSP Headers', link: '/security/api-security/csp-headers' },
        { text: 'API Abuse Prevention', link: '/security/api-security/api-abuse-prevention' },
      ],
    },
  ],

  '/devops/': [
    {
      text: 'DevOps',
      items: [
        { text: 'Overview', link: '/devops/' },
      ],
    },
    {
      text: 'Monitoring',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/devops/monitoring/' },
        { text: 'Prometheus Deep Dive', link: '/devops/monitoring/prometheus-deep-dive' },
        { text: 'Grafana Dashboards', link: '/devops/monitoring/grafana-dashboards' },
        { text: 'Metrics Design', link: '/devops/monitoring/metrics-design' },
        { text: 'Custom Metrics', link: '/devops/monitoring/custom-metrics' },
        { text: 'Monitoring Anti-Patterns', link: '/devops/monitoring/monitoring-antipatterns' },
      ],
    },
    {
      text: 'Logging',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/devops/logging/' },
        { text: 'Structured Logging', link: '/devops/logging/structured-logging' },
        { text: 'Correlation IDs', link: '/devops/logging/correlation-ids' },
        { text: 'Log Aggregation', link: '/devops/logging/log-aggregation' },
        { text: 'Log Levels Strategy', link: '/devops/logging/log-levels-strategy' },
        { text: 'Sensitive Data Redaction', link: '/devops/logging/sensitive-data-redaction' },
      ],
    },
    {
      text: 'Alerting',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/devops/alerting/' },
        { text: 'Alert Design', link: '/devops/alerting/alert-design' },
        { text: 'Severity Levels', link: '/devops/alerting/severity-levels' },
        { text: 'Escalation Policies', link: '/devops/alerting/escalation-policies' },
        { text: 'On-Call Best Practices', link: '/devops/alerting/on-call-best-practices' },
        { text: 'Runbook Templates', link: '/devops/alerting/runbook-templates' },
      ],
    },
    {
      text: 'Deployment Strategies',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/devops/deployment-strategies/' },
        { text: 'Blue-Green', link: '/devops/deployment-strategies/blue-green' },
        { text: 'Canary', link: '/devops/deployment-strategies/canary' },
        { text: 'Rolling Updates', link: '/devops/deployment-strategies/rolling-updates' },
        { text: 'Feature Flags Deployment', link: '/devops/deployment-strategies/feature-flags-deployment' },
        { text: 'Database Migrations', link: '/devops/deployment-strategies/database-migrations' },
        { text: 'Rollback Procedures', link: '/devops/deployment-strategies/rollback-procedures' },
      ],
    },
    {
      text: 'Incident Response',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/devops/incident-response/' },
        { text: 'Incident Classification', link: '/devops/incident-response/incident-classification' },
        { text: 'Communication Templates', link: '/devops/incident-response/communication-templates' },
        { text: 'Postmortem Framework', link: '/devops/incident-response/postmortem-framework' },
        { text: 'War Room Procedures', link: '/devops/incident-response/war-room-procedures' },
        { text: 'Chaos Engineering', link: '/devops/incident-response/chaos-engineering' },
      ],
    },
  ],

  '/performance/': [
    {
      text: 'Performance',
      items: [
        { text: 'Overview', link: '/performance/' },
      ],
    },
    {
      text: 'Profiling',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/performance/profiling/' },
        { text: 'Node.js Profiling', link: '/performance/profiling/nodejs-profiling' },
        { text: 'Go Profiling', link: '/performance/profiling/go-profiling' },
        { text: 'Browser Profiling', link: '/performance/profiling/browser-profiling' },
        { text: 'Database Profiling', link: '/performance/profiling/database-profiling' },
      ],
    },
    {
      text: 'Optimization',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/performance/optimization/' },
        { text: 'Node.js Event Loop', link: '/performance/optimization/nodejs-event-loop' },
        { text: 'Memory Management', link: '/performance/optimization/memory-management' },
        { text: 'V8 Optimization', link: '/performance/optimization/v8-optimization' },
        { text: 'Algorithmic Optimization', link: '/performance/optimization/algorithmic-optimization' },
        { text: 'Concurrency Patterns', link: '/performance/optimization/concurrency-patterns' },
        { text: 'Worker Threads', link: '/performance/optimization/worker-threads' },
      ],
    },
    {
      text: 'Caching Strategies',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/performance/caching-strategies/' },
        { text: 'Application Level', link: '/performance/caching-strategies/application-level' },
        { text: 'Database Level', link: '/performance/caching-strategies/database-level' },
        { text: 'HTTP Caching', link: '/performance/caching-strategies/http-caching' },
        { text: 'Edge Caching', link: '/performance/caching-strategies/edge-caching' },
      ],
    },
    {
      text: 'Database Tuning',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/performance/database-tuning/' },
        { text: 'Query Optimization', link: '/performance/database-tuning/query-optimization' },
        { text: 'Index Strategy', link: '/performance/database-tuning/index-strategy' },
        { text: 'Connection Pool Tuning', link: '/performance/database-tuning/connection-pool-tuning' },
        { text: 'N+1 Problem', link: '/performance/database-tuning/n-plus-one' },
        { text: 'Vacuum & Analyze', link: '/performance/database-tuning/vacuum-analyze' },
      ],
    },
    {
      text: 'Edge Computing',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/performance/edge-computing/' },
        { text: 'Edge Runtime Constraints', link: '/performance/edge-computing/edge-runtime-constraints' },
        { text: 'Cloudflare Workers', link: '/performance/edge-computing/cloudflare-workers' },
        { text: 'Deno Deploy', link: '/performance/edge-computing/deno-deploy' },
        { text: 'Vercel Edge', link: '/performance/edge-computing/vercel-edge' },
      ],
    },
  ],

  '/data-engineering/': [
    {
      text: 'Data Engineering',
      items: [
        { text: 'Overview', link: '/data-engineering/' },
      ],
    },
    {
      text: 'ETL Patterns',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/data-engineering/etl-patterns/' },
        { text: 'ETL vs ELT', link: '/data-engineering/etl-patterns/etl-vs-elt' },
        { text: 'Batch Processing', link: '/data-engineering/etl-patterns/batch-processing' },
        { text: 'Incremental Loads', link: '/data-engineering/etl-patterns/incremental-loads' },
        { text: 'Idempotent Pipelines', link: '/data-engineering/etl-patterns/idempotent-pipelines' },
        { text: 'Error Handling', link: '/data-engineering/etl-patterns/error-handling' },
      ],
    },
    {
      text: 'Stream Processing',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/data-engineering/stream-processing/' },
        { text: 'Windowing', link: '/data-engineering/stream-processing/windowing' },
        { text: 'Watermarks', link: '/data-engineering/stream-processing/watermarks' },
        { text: 'Exactly-Once Processing', link: '/data-engineering/stream-processing/exactly-once-processing' },
        { text: 'State Management', link: '/data-engineering/stream-processing/state-management' },
        { text: 'Backpressure', link: '/data-engineering/stream-processing/backpressure' },
      ],
    },
    {
      text: 'Data Modeling',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/data-engineering/data-modeling/' },
        { text: 'Dimensional Modeling', link: '/data-engineering/data-modeling/dimensional-modeling' },
        { text: 'Data Vault', link: '/data-engineering/data-modeling/data-vault' },
        { text: 'Slowly Changing Dimensions', link: '/data-engineering/data-modeling/slowly-changing-dimensions' },
        { text: 'Normalization & Denormalization', link: '/data-engineering/data-modeling/normalization-denormalization' },
        { text: 'Schema Evolution', link: '/data-engineering/data-modeling/schema-evolution' },
      ],
    },
    {
      text: 'Pipeline Patterns',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/data-engineering/pipeline-patterns/' },
        { text: 'CDC Patterns', link: '/data-engineering/pipeline-patterns/cdc-patterns' },
        { text: 'Data Quality Checks', link: '/data-engineering/pipeline-patterns/data-quality-checks' },
        { text: 'Data Lineage', link: '/data-engineering/pipeline-patterns/data-lineage' },
        { text: 'Orchestration', link: '/data-engineering/pipeline-patterns/orchestration' },
        { text: 'Testing Data Pipelines', link: '/data-engineering/pipeline-patterns/testing-data-pipelines' },
      ],
    },
  ],

  '/prompt-engineering/': [
    {
      text: 'Prompt Engineering',
      items: [
        { text: 'Overview', link: '/prompt-engineering/' },
      ],
    },
    {
      text: 'Engineering Prompts',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/prompt-engineering/engineering-prompts/' },
        { text: 'Debugging Prompts', link: '/prompt-engineering/engineering-prompts/debugging-prompts' },
        { text: 'Architecture Review', link: '/prompt-engineering/engineering-prompts/architecture-review-prompts' },
        { text: 'Code Generation', link: '/prompt-engineering/engineering-prompts/code-generation-prompts' },
        { text: 'Refactoring', link: '/prompt-engineering/engineering-prompts/refactoring-prompts' },
        { text: 'Testing', link: '/prompt-engineering/engineering-prompts/testing-prompts' },
      ],
    },
    {
      text: 'Product Prompts',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/prompt-engineering/product-prompts/' },
        { text: 'PRD Prompts', link: '/prompt-engineering/product-prompts/prd-prompts' },
        { text: 'User Story Prompts', link: '/prompt-engineering/product-prompts/user-story-prompts' },
        { text: 'Competitive Analysis', link: '/prompt-engineering/product-prompts/competitive-analysis-prompts' },
        { text: 'Go-to-Market', link: '/prompt-engineering/product-prompts/go-to-market-prompts' },
      ],
    },
    {
      text: 'UI Prompts',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/prompt-engineering/ui-prompts/' },
        { text: 'Component Generation', link: '/prompt-engineering/ui-prompts/component-generation-prompts' },
        { text: 'Design System', link: '/prompt-engineering/ui-prompts/design-system-prompts' },
        { text: 'Accessibility', link: '/prompt-engineering/ui-prompts/accessibility-prompts' },
        { text: 'Responsive Design', link: '/prompt-engineering/ui-prompts/responsive-design-prompts' },
      ],
    },
    {
      text: 'Architecture Prompts',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/prompt-engineering/architecture-prompts/' },
        { text: 'System Design', link: '/prompt-engineering/architecture-prompts/system-design-prompts' },
        { text: 'Scaling', link: '/prompt-engineering/architecture-prompts/scaling-prompts' },
        { text: 'Migration', link: '/prompt-engineering/architecture-prompts/migration-prompts' },
        { text: 'Cost Optimization', link: '/prompt-engineering/architecture-prompts/cost-optimization-prompts' },
      ],
    },
  ],

  '/ui-design-systems/': [
    {
      text: 'UI & Design Systems',
      items: [
        { text: 'Overview', link: '/ui-design-systems/' },
      ],
    },
    {
      text: 'Component Patterns',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/ui-design-systems/component-patterns/' },
        { text: 'Atomic Design', link: '/ui-design-systems/component-patterns/atomic-design' },
        { text: 'Compound Components', link: '/ui-design-systems/component-patterns/compound-components' },
        { text: 'Render Props & Hooks', link: '/ui-design-systems/component-patterns/render-props-hooks' },
        { text: 'Controlled vs Uncontrolled', link: '/ui-design-systems/component-patterns/controlled-uncontrolled' },
        { text: 'Polymorphic Components', link: '/ui-design-systems/component-patterns/polymorphic-components' },
        { text: 'Slot Pattern', link: '/ui-design-systems/component-patterns/slot-pattern' },
        { text: 'Headless Components', link: '/ui-design-systems/component-patterns/headless-components' },
      ],
    },
    {
      text: 'Typography',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/ui-design-systems/typography/' },
        { text: 'Type Scale', link: '/ui-design-systems/typography/type-scale' },
        { text: 'Font Loading', link: '/ui-design-systems/typography/font-loading' },
        { text: 'Variable Fonts', link: '/ui-design-systems/typography/variable-fonts' },
        { text: 'Responsive Typography', link: '/ui-design-systems/typography/responsive-typography' },
      ],
    },
    {
      text: 'Color Tokens',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/ui-design-systems/color-tokens/' },
        { text: 'Color Theory', link: '/ui-design-systems/color-tokens/color-theory' },
        { text: 'Semantic Tokens', link: '/ui-design-systems/color-tokens/semantic-tokens' },
        { text: 'Palette Generation', link: '/ui-design-systems/color-tokens/palette-generation' },
        { text: 'Contrast & Accessibility', link: '/ui-design-systems/color-tokens/contrast-accessibility' },
      ],
    },
    {
      text: 'Spacing & Layout',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/ui-design-systems/spacing-layout/' },
        { text: 'Spacing Scale', link: '/ui-design-systems/spacing-layout/spacing-scale' },
        { text: 'Layout Patterns', link: '/ui-design-systems/spacing-layout/layout-patterns' },
        { text: 'Responsive Breakpoints', link: '/ui-design-systems/spacing-layout/responsive-breakpoints' },
        { text: 'Container Queries', link: '/ui-design-systems/spacing-layout/container-queries' },
      ],
    },
    {
      text: 'Accessibility',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/ui-design-systems/accessibility/' },
        { text: 'ARIA Deep Dive', link: '/ui-design-systems/accessibility/aria-deep-dive' },
        { text: 'Keyboard Navigation', link: '/ui-design-systems/accessibility/keyboard-navigation' },
        { text: 'Screen Reader Patterns', link: '/ui-design-systems/accessibility/screen-reader-patterns' },
        { text: 'Focus Management', link: '/ui-design-systems/accessibility/focus-management' },
        { text: 'Testing Accessibility', link: '/ui-design-systems/accessibility/testing-accessibility' },
      ],
    },
    {
      text: 'Dark Mode',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/ui-design-systems/dark-mode/' },
        { text: 'Token Mapping', link: '/ui-design-systems/dark-mode/token-mapping' },
        { text: 'Implementation Patterns', link: '/ui-design-systems/dark-mode/implementation-patterns' },
        { text: 'Image Handling', link: '/ui-design-systems/dark-mode/image-handling' },
        { text: 'System Preference Detection', link: '/ui-design-systems/dark-mode/system-preference-detection' },
      ],
    },
    {
      text: 'Animations',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/ui-design-systems/animations/' },
        { text: 'Timing Curves', link: '/ui-design-systems/animations/timing-curves' },
        { text: 'Motion Principles', link: '/ui-design-systems/animations/motion-principles' },
        { text: 'CSS Animations', link: '/ui-design-systems/animations/css-animations' },
        { text: 'Framer Motion Patterns', link: '/ui-design-systems/animations/framer-motion-patterns' },
        { text: 'Gesture Animations', link: '/ui-design-systems/animations/gesture-animations' },
        { text: 'Performance', link: '/ui-design-systems/animations/performance-considerations' },
      ],
    },
  ],

  '/production-blueprints/': [
    {
      text: 'Production Blueprints',
      items: [
        { text: 'Overview', link: '/production-blueprints/' },
      ],
    },
    {
      text: 'Auth Service',
      collapsed: false,
      items: [
        { text: 'Overview', link: '/production-blueprints/auth-service/' },
        { text: 'Architecture', link: '/production-blueprints/auth-service/architecture' },
        { text: 'API Contracts', link: '/production-blueprints/auth-service/api-contracts' },
        { text: 'Database Schema', link: '/production-blueprints/auth-service/database-schema' },
        { text: 'Deployment', link: '/production-blueprints/auth-service/deployment' },
        { text: 'Scaling Plan', link: '/production-blueprints/auth-service/scaling-plan' },
      ],
    },
    {
      text: 'Billing Engine',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/production-blueprints/billing-engine/' },
        { text: 'Architecture', link: '/production-blueprints/billing-engine/architecture' },
        { text: 'Stripe Integration', link: '/production-blueprints/billing-engine/stripe-integration' },
        { text: 'Subscription Models', link: '/production-blueprints/billing-engine/subscription-models' },
        { text: 'Webhook Handling', link: '/production-blueprints/billing-engine/webhook-handling' },
        { text: 'Idempotency', link: '/production-blueprints/billing-engine/idempotency' },
      ],
    },
    {
      text: 'Notification Service',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/production-blueprints/notification-service/' },
        { text: 'Architecture', link: '/production-blueprints/notification-service/architecture' },
        { text: 'Channel Adapters', link: '/production-blueprints/notification-service/channel-adapters' },
        { text: 'Template Engine', link: '/production-blueprints/notification-service/template-engine' },
        { text: 'Rate Limiting', link: '/production-blueprints/notification-service/rate-limiting' },
        { text: 'Delivery Tracking', link: '/production-blueprints/notification-service/delivery-tracking' },
      ],
    },
    {
      text: 'Realtime Pipeline',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/production-blueprints/realtime-pipeline/' },
        { text: 'Architecture', link: '/production-blueprints/realtime-pipeline/architecture' },
        { text: 'Ingestion Layer', link: '/production-blueprints/realtime-pipeline/ingestion-layer' },
        { text: 'Processing Layer', link: '/production-blueprints/realtime-pipeline/processing-layer' },
        { text: 'Storage Layer', link: '/production-blueprints/realtime-pipeline/storage-layer' },
        { text: 'Query Layer', link: '/production-blueprints/realtime-pipeline/query-layer' },
      ],
    },
    {
      text: 'Rate Limiter',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/production-blueprints/rate-limiter/' },
        { text: 'Algorithms', link: '/production-blueprints/rate-limiter/algorithms' },
        { text: 'Distributed Rate Limiting', link: '/production-blueprints/rate-limiter/distributed-rate-limiting' },
        { text: 'Redis Implementation', link: '/production-blueprints/rate-limiter/redis-implementation' },
        { text: 'API Design', link: '/production-blueprints/rate-limiter/api-design' },
      ],
    },
    {
      text: 'Job Queue',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/production-blueprints/job-queue/' },
        { text: 'Architecture', link: '/production-blueprints/job-queue/architecture' },
        { text: 'Worker Patterns', link: '/production-blueprints/job-queue/worker-patterns' },
        { text: 'Retry Strategies', link: '/production-blueprints/job-queue/retry-strategies' },
        { text: 'Priority Queues', link: '/production-blueprints/job-queue/priority-queues' },
        { text: 'Monitoring', link: '/production-blueprints/job-queue/monitoring' },
      ],
    },
    {
      text: 'A/B Testing',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/production-blueprints/ab-testing/' },
        { text: 'Architecture', link: '/production-blueprints/ab-testing/architecture' },
        { text: 'Statistical Significance', link: '/production-blueprints/ab-testing/statistical-significance' },
        { text: 'Feature Flag Integration', link: '/production-blueprints/ab-testing/feature-flag-integration' },
        { text: 'Assignment Algorithms', link: '/production-blueprints/ab-testing/assignment-algorithms' },
        { text: 'Analysis Pipeline', link: '/production-blueprints/ab-testing/analysis-pipeline' },
      ],
    },
    {
      text: 'Analytics Pipeline',
      collapsed: true,
      items: [
        { text: 'Overview', link: '/production-blueprints/analytics-pipeline/' },
        { text: 'Architecture', link: '/production-blueprints/analytics-pipeline/architecture' },
        { text: 'Event Schema', link: '/production-blueprints/analytics-pipeline/event-schema' },
        { text: 'Ingestion', link: '/production-blueprints/analytics-pipeline/ingestion' },
        { text: 'ClickHouse Storage', link: '/production-blueprints/analytics-pipeline/storage-clickhouse' },
        { text: 'Query Engine', link: '/production-blueprints/analytics-pipeline/query-engine' },
      ],
    },
  ],
}
